### ISSUE TITLE
Surround each line with a tag

### ISSUE THREAD

**Issue by semaf** [BalduinLandolt/vs-code-surround-with-tag#13]
Hey,

I am somehow confused if your plugin can surround each line with the given tag?

For example:

```
1
2
3
4
5
```

should be

```
<li>1</li>
<li>2</li>
<li>3</li>
<li>4</li>
<li>5</li>
```

**Comment by BalduinLandolt** [comment]
Hi! I'm glad someone is using the plugin. :)

Yes, that's possible. Given the following document:

```xml
<div>
  1
  2
  3
  4
</div>
```

you would have to use multi cursor selection (for me it works with dragging while holding the middle mouse button down), and select the individual instances:

```xml
<div>
  |1|
  |2|
  |3|
  |4|
</div>
```

(the pipes indicate from where to where you select)

the you can just hit `Ctrl/Cmd + i` (or whatever shortcut you use and select `li`, and you'll have this result:

```xml
<div>
  <li>1</li>
  <li>2</li>
  <li>3</li>
  <li>4</li>
</div>
```

sadly, selecting them in one selection like this won't work:
```
<div>
  |1
  2
  3
  4|
</div>
```

Another thing you can do, is use emmet abbreviations: Hit  `Ctrl/Cmd + i`  and enter `li*4`, then you get the tags and can copy the contents into them.

I hope this helps you. If you still have questions, don't hesitate to ask!

**Comment by semaf** [comment]
Got it out. Thank you

Multi cursor selecting the area with `CTRL + ALT + CURSOR`, than `SHIFT + CURSOR` (LEFT or RIGHT), than `CTRL + i` and at least type `<li>` did it.

**Comment by BalduinLandolt** [comment]
Good, I will mark this as closed then. Feel free to open another issue if you have any more questions
